# Baut tools/sdxl/jobs-flux-portraets.json aus portraits.json: je Wesen eine eigene Bildbeschreibung (FLUX liest
# ganze Sätze) und drei Varianten (frontal / nach rechts gewandt – Monster-Token werden bei Blick nach rechts nicht
# gespiegelt). Korrigiert falsche Zuordnungen der alten Liste (Grottenschrat = Bugbear, Drinne = Drider, Plapperndes
# Hundertmaul = Gibbering Mouther).
import json
import sys
from pathlib import Path

SDXL = Path(sys.argv[1])
alt = {j["id"]: j for j in json.loads((SDXL / "portraits.json").read_text(encoding="utf-8"))}

FARBEN = {
    "rot": ("red", "crimson-red scales, swept-back horns, a frilled jaw and smoke curling from its nostrils"),
    "blau": ("blue", "deep blue scales, one large horn on its snout, frills along the jaw and crackling sparks of lightning"),
    "gruen": ("green", "emerald-green scales, a crest running from the brow down the neck, a long frilled jaw and wisps of green mist"),
    "schwarz": ("black", "glossy black scales, forward-curving horns, a skull-like face with deep-set eyes and acid dripping from its jaws"),
    "weiss": ("white", "icy white scales, a sharp crest and spiked brow, frost on its scales and cold breath"),
    "gold": ("gold", "gleaming gold scales, long whisker-like tendrils at the jaw, two smooth horns and a wise noble face"),
    "silber": ("silver", "shining silver scales, a smooth frill from the head down the neck and a noble face"),
    "bronze": ("bronze", "bronze scales with a green patina, a ribbed frill, horns sweeping back and drops of sea spray"),
    "messing": ("brass", "brass-coloured scales, a broad plate-like crest on its head and a pointed chin"),
    "kupfer": ("copper", "copper-coloured scales, ridged horns sweeping back in segments and a sly expression"),
}
ALTER = {
    "nestling": ("wyrmling", "a dragon hatchling, small and slender with big eyes and short stubby horns, {f}"),
    "junger": ("young", "a young dragon, lean and sleek with short horns, {f}"),
    "ausgewachsener": ("adult", "a huge adult dragon with a powerful jaw and long horns, {f}"),
    "uralter": ("ancient", "a colossal ancient dragon with a massive head, long weathered horns, battle scars and thick old scales, {f}"),
}
GANZ = "the whole shape"

L = {
    "aboleth": ("an aboleth", "a huge primeval fish-like aberration with a long eel-like body, three red eyes stacked one above the other, four long tentacles and slimy blue-green skin covered in mucus"),
    "adeliger": ("a human noble", "a proud haughty face, well-groomed hair, a fine embroidered doublet under a polished steel breastplate and a gold chain"),
    "adler": ("an eagle", "a real eagle with brown feathers, a white head, a hooked yellow beak and fierce golden eyes"),
    "akolyth": ("a human acolyte", "a young devout face, a simple hooded grey robe and a wooden holy symbol on a cord"),
    "androsphinx": ("an androsphinx", "the body of a huge lion with great feathered wings and a bearded male human head wearing a regal striped headdress"),
    "ankheg": ("an ankheg", "a giant burrowing insect with a hard brown chitinous shell, long antennae and huge mandibles dripping with acid"),
    "assassine": ("a human assassin", "a dark hood, a black scarf over the lower face, cold narrow eyes and dark studded leather armour"),
    "atterkopp": ("an ettercap", "a hunched spider-like humanoid with purple-black hairy skin, a bulbous head with many small eyes, venomous fangs and long clawed fingers"),
    "axtschnabel": ("an axe beak", "a tall flightless bird with grey-brown feathers, a long strong neck and a huge axe-shaped hooked beak"),
    "azer": ("an azer", "a stocky dwarf-like being made of living brass, with a beard and hair of flickering flames and glowing orange eyes"),
    "balor": ("a balor", "a towering fiend with dark red skin, a horned bestial face, huge bat-like wings and a body wreathed in flames"),
    "bandit": ("a human bandit", "a scruffy scarred face, a hood and a cloth scarf, worn brown leather armour"),
    "banditenhauptmann": ("a human bandit captain", "a confident grin, a trimmed beard, a wide-brimmed hat with a feather, studded leather armour and a red sash"),
    "bartteufel": ("a bearded devil", "a humanoid fiend with reptilian red-brown skin, small horns, pointed ears and a writhing beard of snake-like tendrils"),
    "basilisk": ("a basilisk", "a long eight-legged reptile with dull brown scales, a row of spines along its back, a broad head and glowing pale green eyes"),
    "baumhirte": ("a treant", "an ancient walking oak tree with a face of gnarled bark, deep-set glowing eyes, mossy branches for hair and a beard of lichen"),
    "behir": ("a behir", "a huge serpentine monster with many legs, deep blue scales, a crocodile-like horned head and crackling blue lightning"),
    "belebte-ruestung": ("an animated suit of armour", "an empty suit of dented steel plate armour standing by itself, the open visor of its helmet showing only darkness inside"),
    "berserker": ("a human berserker", "a wild braided beard, war paint, a bear-fur cloak over the shoulders and a fierce battle-hungry expression"),
    "blutfalke": ("a blood hawk", "a hawk with crimson-red feathers, a sharp hooked beak and fierce red eyes"),
    "blutmuecke": ("a stirge", "a bat-like creature with leathery wings, four thin insect legs and a long needle-like proboscis, reddish-brown skin"),
    "braunbaer": ("a brown bear", "a real brown bear with thick shaggy brown fur, small dark eyes and a broad snout"),
    "chimaere": ("a chimera", "a monster with a lion's body and three heads side by side – a lion, a horned goat and a red dragon – and leathery wings"),
    "chuul": ("a chuul", "a large lobster-like aberration with a hard greenish-brown carapace, huge pincers and writhing tentacles around its mouth"),
    "couatl": ("a couatl", "a celestial feathered serpent with rainbow-coloured feathered wings, golden scales and wise glowing eyes"),
    "dachs": ("a badger", "a real badger with grey fur and a black and white striped face"),
    "dampf-mephit": ("a steam mephit", "a small impish creature made of scalding white steam and hissing vapour, with tiny wings and bright eyes"),
    "deva": ("a deva", "a tall angel with silver skin, white feathered wings, short silver hair and luminous eyes, in a white and gold robe"),
    "dogge": ("a mastiff", "a real mastiff dog with a massive head, short fawn fur, drooping jowls and a dark muzzle"),
    "doppelgaenger": ("a doppelganger", "a gaunt grey-skinned humanoid with a hairless head, large blank white eyes and an unfinished, featureless face"),
    "drachenschildkroete": ("a dragon turtle", "an enormous sea creature with a horned dragon's head with green-gold scales and a huge rough shell, water streaming off it"),
    "dretch": ("a dretch", "a small pot-bellied fiend with sickly grey-pink skin, spindly limbs, a toothy grin and small horns"),
    "drinne": ("a drider", "the upper body of a dark-skinned elf with long white hair and red eyes fused to the body of a giant black spider, wearing a dark leather jerkin"),
    "drow-elf": ("a drow elf", "dark grey-black skin, long white hair, red eyes and pointed ears, a fine black chain shirt over a dark tunic"),
    "druide": ("a human druid", "an old weathered face, a long beard woven with leaves, a green-brown hooded robe and a necklace of bones and feathers"),
    "dryade": ("a dryad", "a slender fey woman whose skin looks like smooth bark, hair of green leaves and flowers, wearing a dress of woven leaves"),
    "dschinni": ("a djinni", "a tall blue-skinned genie with a turban, golden jewellery and an open silk vest, whose lower body becomes a swirling cloud of wind"),
    "duergar": ("a duergar", "a grey-skinned bald dwarf with a long grey beard, a stern face and faintly glowing eyes, in dark scale armour"),
    "duestermantel": ("a darkmantle", "a small octopus-like creature with a dark cloak-like body of skin stretched between its tentacles and a hard beak, hanging from a cave ceiling"),
    "eber": ("a wild boar", "a real wild boar with coarse dark bristly fur, small fierce eyes and sharp curved tusks"),
    "echsenmensch": ("a lizardfolk warrior", "a reptilian humanoid with green scales, a crocodile-like snout, a feather crest and a necklace of bones"),
    "eidechse": ("a lizard", "a real small lizard with green-brown scales and a long tail"),
    "einhorn": ("a unicorn", "a pure white horse with a flowing silver mane and one long spiral horn on its forehead, gentle wise eyes"),
    "eis-mephit": ("an ice mephit", "a small impish creature made of jagged pale blue ice, with tiny frosty wings and bright cold eyes"),
    "eisbaer": ("a polar bear", "a real polar bear with thick white fur and a black nose"),
    "eisengolem": ("an iron golem", "a towering humanoid statue of dark iron with a helmet-like head, riveted plates and a green glow in its eye slits"),
    "eisteufel": ("an ice devil", "a tall insect-like fiend with a pale blue-white exoskeleton, a mandibled bug-like head and a spiked tail"),
    "elch": ("an elk", "a real elk with brown fur and huge branching antlers"),
    "elefant": ("an elephant", "a real elephant with grey wrinkled skin, large ears, long ivory tusks and a curling trunk"),
    "erdelementar": ("an earth elemental", "a hulking body of rock, soil and stone with a craggy head and two glowing amber eyes, gravel trickling from it"),
    "erinnye": ("an erinyes", "a stern fallen angel with black feathered wings and small horns, in black steel plate armour"),
    "erwachter-baum": ("an awakened tree", "a gnarled old tree with a living face in its bark, branches like arms and roots like legs"),
    "erwachter-busch": ("an awakened shrub", "a small leafy bush with a face of twigs and two dark knot-hole eyes, roots like little feet"),
    "erzmagier": ("a human archmage", "an old wise face, a long white beard, a deep blue robe embroidered with silver runes and a staff with a glowing crystal"),
    "ettin": ("an ettin", "a huge brutish giant with two ugly heads side by side, tangled hair and crude furs and leather"),
    "eule": ("an owl", "a real owl with brown and white feathers and big round yellow eyes"),
    "eulenbaer": ("an owlbear", "a huge bear-like monster with the head of an owl, a hooked beak, brown feathers on its head and shoulders and shaggy fur"),
    "falke": ("a hawk", "a real hawk with brown feathers, a hooked beak and sharp yellow eyes"),
    "feengeist": ("a sprite", "a tiny fey with dragonfly wings, pointed ears and a fierce little face, in armour of leaves and bark"),
    "feuerelementar": ("a fire elemental", "a roaring living flame in vaguely humanoid shape with a head of fire and two bright white glowing eyes"),
    "feuerriese": ("a fire giant", "a towering giant with coal-black skin and a fiery orange beard and hair, in heavy dark steel plate armour"),
    "fledermaus": ("a bat", "a real bat with leathery wings, big ears and a small furry face"),
    "fledermausschwarm": ("a swarm of bats", "a swirling cloud of many black bats with leathery wings, beady eyes and small fangs"),
    "fleischgolem": ("a flesh golem", "a hulking patchwork humanoid of stitched grey-green flesh with metal bolts in its neck and dull eyes"),
    "fliegende-schlange": ("a flying snake", "a slender brightly coloured snake with small feathered wings"),
    "fliegendes-schwert": ("a flying sword", "a magical longsword floating upright in the air by itself, its steel blade gleaming"),
    "flimmerhund": ("a blink dog", "a big shaggy wolfhound with shimmering blue-grey fur and intelligent eyes, its outline flickering faintly"),
    "frosch": ("a frog", "a real frog with green skin and golden eyes"),
    "frostriese": ("a frost giant", "a towering giant with pale blue-white skin and a braided icy white beard, in mismatched furs and scavenged armour plates"),
    "gallertwuerfel": ("a gelatinous cube", "a large transparent green cube of jelly with bones, coins and a rusty sword suspended inside"),
    "gargyl": ("a gargoyle", "a living grey stone creature with a demonic horned face, stone bat wings and clawed hands"),
    "geier": ("a vulture", "a real vulture with a bald pink head, dark brown feathers and a hooked beak"),
    "geist": ("a ghost", "a translucent pale blue spirit of a sorrowful human in tattered ghostly clothes, with glowing hollow eyes"),
    "geisternaga": ("a spirit naga", "a huge black serpent with a gaunt human-like head with dark eyes and long black hair"),
    "gemeiner": ("a human commoner", "a simple villager with a tired kind face, plain linen clothes and a wool cap"),
    "ghul": ("a ghoul", "a gaunt undead with grey-green skin stretched over bones, a long tongue, sharp teeth and clawed hands, in rotten rags"),
    "giftschlange": ("a venomous snake", "a real venomous snake with patterned scales, a raised head and bared fangs"),
    "giftschlangenschwarm": ("a swarm of venomous snakes", "a writhing mass of many venomous snakes with patterned scales and bared fangs"),
    "glabrezu": ("a glabrezu", "a large fiend with a canine horned head, rough red-brown skin and four arms, two of them ending in huge crab-like pincers"),
    "gladiator": ("a human gladiator", "a scarred muscular fighter with a crested helmet, a shoulder guard and studded leather armour"),
    "gnoll": ("a gnoll", "a hyena-headed humanoid with spotted fur, a mane and sharp teeth, in crude fur and hide armour"),
    "gnom-tiefengnom-svirfneblin": ("a deep gnome", "a small bald gnome with grey stone-like skin, a large nose and deep-set eyes, in a chain shirt"),
    "goblin": ("a goblin", "a small wiry humanoid with green skin, long pointed ears, a wide mouth with sharp teeth and yellow eyes, in brown leather armour"),
    "gorgone": ("a gorgon", "a huge bull-like monster covered in iron-grey metallic scales with large horns and green vapour around its nostrils"),
    "grauschlick": ("a gray ooze", "a shapeless puddle of glistening grey slime that looks like wet stone"),
    "greif": ("a griffon", "a beast with the head, wings and front talons of a golden eagle and the body of a lion"),
    "grick": ("a grick", "a worm-like creature with a grey-green rubbery body and a beaked mouth surrounded by four tentacles"),
    "grimlock": ("a grimlock", "a grey-skinned humanoid with no eyes, a scarred face, sharp teeth and long black hair, in simple rags"),
    "grottenschrat": ("a bugbear", "a tall hairy goblinoid with coarse brown fur, a bear-like face with a flat nose, pointed ears and sharp teeth, in fur and hide armour"),
    "gruftschrecken": ("a wight", "an undead warrior with dry grey skin, sunken glowing red eyes and long fingernails, in old studded leather armour"),
    "grul": ("a ghast", "a hideous gaunt undead with grey-green skin, a long tongue, sharp teeth and glowing yellow eyes"),
    "gruene-vettel": ("a green hag", "a hideous old woman with green skin, long tangled black hair, a hooked nose, yellow eyes and long claws, in rags"),
    "gynosphinx": ("a gynosphinx", "the body of a lion with great feathered wings and the head of a wise woman wearing a golden headdress"),
    "halbroter-drachenveteran": ("a half-dragon veteran", "a human veteran warrior with half-dragon features – patches of red scales on the face, small horns and reptile eyes – in full steel plate armour"),
    "harpyie": ("a harpy", "a wild-haired woman with a hideous face, her body covered in dark feathers, large feathered wings for arms and taloned bird legs"),
    "hezrou": ("a hezrou", "a huge toad-like fiend with rough green-brown skin, a wide mouth full of fangs and spikes along its back"),
    "hobgoblin": ("a hobgoblin", "a disciplined goblinoid warrior with red-orange skin, a flat face and sharp teeth, in a full chainmail hauberk"),
    "hoellenhund": ("a hell hound", "a large black dog with rust-red eyes, smoke and flames escaping from its jaws"),
    "hoellenschlundteufel": ("a pit fiend", "a huge winged devil with dark red scaly skin, large horns, a fanged face and huge bat-like wings"),
    "homunkulus": ("a homunculus", "a tiny winged humanoid creature with leathery green skin, bat wings, a pointed face and a long tail"),
    "hornteufel": ("a horned devil", "a tall fiend with scaly dark skin, large curving horns, bat wings and a fierce face"),
    "huegelriese": ("a hill giant", "a huge dull-witted giant with tanned skin, a lumpy face and crude hide clothes"),
    "hyaene": ("a hyena", "a real hyena with spotted fur and a powerful jaw"),
    "hydra": ("a hydra", "a huge reptilian monster with five long-necked snake-like heads, green scales and sharp teeth"),
    "ifriti": ("an efreeti", "a huge fiery genie with red skin, flaming hair, a black beard and golden jewellery, its lower body a swirl of smoke and fire"),
    "insektenschwarm": ("a swarm of insects", "a swirling cloud of many beetles, flies and wasps"),
    "irrlicht": ("a will-o'-wisp", "a floating ball of pale blue ghostly light glowing in the darkness of a misty swamp"),
    "jagdhai": ("a hunter shark", "a real shark with grey skin and a gaping mouth with rows of sharp teeth, underwater"),
    "kamel": ("a camel", "a real camel with tan fur and a hump"),
    "katze": ("a cat", "a real tabby cat with green eyes"),
    "kettenteufel": ("a chain devil", "a humanoid fiend wrapped in hooked iron chains, with pale scarred skin and a cruel face"),
    "killerwal": ("a killer whale", "a real orca with black and white skin, underwater"),
    "klingenteufel": ("a barbed devil", "a tall fiend covered in sharp barbs and spines, with reddish skin and burning eyes"),
    "knochenteufel": ("a bone devil", "a tall gaunt fiend with dry skin stretched over its bones, a skull-like head, insect wings and a scorpion tail"),
    "kobold": ("a kobold", "a small reptilian humanoid with reddish-brown scales, a dog-like snout, small horns and a long tail, in simple clothes"),
    "krabbe": ("a crab", "a real crab with a red-brown shell and pincers"),
    "kraken": ("a kraken", "a gigantic squid-like sea monster with a huge eye, massive tentacles and a dark rugged body rising from stormy waves"),
    "kreischer": ("a shrieker", "a giant purple mushroom with a broad cap growing in a dark cave"),
    "krokodil": ("a crocodile", "a real crocodile with rough green-grey scales and an open toothy mouth"),
    "kultfanatiker": ("a human cult fanatic", "a shaved head, painted symbols on the face and a crazed look, a dark hooded robe over leather armour"),
    "kultist": ("a human cultist", "a dark hooded robe with a strange sigil and a shadowed face"),
    "lamia": ("a lamia", "the upper body of a dark-haired woman with golden jewellery and a silk top and the lower body of a lion"),
    "landhai": ("a bulette", "a massive armoured burrowing monster with a shark-like head, a huge mouth, grey-blue armour plates and a dorsal fin"),
    "lehmgolem": ("a clay golem", "a large humanoid sculpted from reddish-brown clay with a crude face and runes carved on its body"),
    "lemure": ("a lemure", "a shapeless lump of pink-grey molten flesh with a vaguely human head"),
    "lich": ("a lich", "an undead sorcerer with a skeletal face, glowing eyes and dry skin, wearing a crown and dark tattered robes"),
    "loewe": ("a lion", "a real male lion with a thick golden mane"),
    "luftelementar": ("an air elemental", "a spinning tornado of howling wind, dust and lightning with two small glowing white lights inside the swirl"),
    "magier": ("a human mage", "a short beard, a purple hooded robe with arcane symbols and a soft glow at the fingertips"),
    "magma-mephit": ("a magma mephit", "a small impish creature of molten rock and glowing lava, with tiny wings and bright eyes"),
    "magmin": ("a magmin", "a small stout creature made of cracked black magma with orange fire glowing through the cracks and a flaming head"),
    "mammut": ("a mammoth", "a real woolly mammoth with shaggy brown fur and long curved tusks"),
    "mantikor": ("a manticore", "a monster with a lion's body, a human-like head with a mane, bat-like wings and a tail ending in iron spikes"),
    "mantler": ("a cloaker", "a dark manta-like creature that looks like a black leather cloak, with glowing red eyes"),
    "marilith": ("a marilith", "a fiend with the upper body of a woman in ornate armour with six arms each holding a sword and the lower body of a great green snake"),
    "maultier": ("a mule", "a real mule with brown fur and long ears"),
    "medusa": ("a medusa", "a woman with scaly green skin and a head of living hissing snakes instead of hair, wearing a dark robe"),
    "meervolk": ("a merfolk", "a person with blue-green skin, a shell necklace and seaweed in the hair, the lower body a fish tail"),
    "menschenaffe": ("an ape", "a real gorilla-like ape with dark fur"),
    "mimik": ("a mimic", "a wooden treasure chest with a huge mouth of sharp teeth and a long sticky tongue"),
    "minotaurus": ("a minotaur", "a huge muscular humanoid with the head of a bull, large horns, a ring in its nose and a leather harness"),
    "minotaurus-skelett": ("a minotaur skeleton", "the undead skeleton of a minotaur with a horned bull skull and glowing eyes"),
    "modernder-schlurfer": ("a shambling mound", "a hulking mass of rotting vegetation, vines, moss and mud in a vaguely humanoid shape"),
    "mumie": ("a mummy", "an undead wrapped in ancient dirty linen bandages with glowing eyes and dried skin showing through"),
    "mumienfuerst": ("a mummy lord", "an ancient undead king wrapped in linen bandages, wearing a golden headdress and jewellery, with glowing eyes"),
    "nachtmahr": ("a nightmare", "a black demonic horse with a mane and hooves of flame, glowing red eyes and smoke from its nostrils"),
    "nachtvettel": ("a night hag", "a hideous old woman with blue-black skin, wild white hair, small horns, glowing red eyes and long claws, in dark rags"),
    "nalfeshnee": ("a nalfeshnee", "a huge fiend with a boar-like head, an ape-like body and tiny feathered wings"),
    "nashorn": ("a rhinoceros", "a real rhinoceros with thick grey skin and a large horn"),
    "ockergallerte": ("an ochre jelly", "a shapeless blob of yellow-brown translucent slime"),
    "oger": ("an ogre", "a large brutish giant with a big head, small eyes, crooked teeth and dirty skin, in crude fur and hide armour"),
    "ogerzombie": ("an ogre zombie", "a rotting undead ogre with grey decaying skin, a slack jaw and dull eyes, in rotten rags"),
    "oktopus": ("an octopus", "a real octopus with red-brown skin and curling tentacles, underwater"),
    "oni": ("an oni", "a tall ogre-like being with blue skin, two small horns, long black hair and sharp tusks, in a full chainmail hauberk"),
    "ork": ("an orc", "a muscular humanoid with grey-green skin, small tusks, a heavy brow and pointed ears, in fur and hide armour"),
    "otyugh": ("an otyugh", "a bloated three-legged aberration with a huge mouth full of teeth, two tentacle arms with spiked tips and an eye stalk"),
    "panther": ("a panther", "a real black panther with sleek black fur and green eyes"),
    "pavian": ("a baboon", "a real baboon with brown fur and a long snout"),
    "pegasus": ("a pegasus", "a white winged horse with large feathered wings"),
    "pferdegreif": ("a hippogriff", "a beast with the head, wings and front legs of an eagle and the body of a horse"),
    "phasenspinne": ("a phase spider", "a giant spider with a black and violet shimmering body, its outline partly fading away"),
    "planetar": ("a planetar", "a large angel with emerald-green skin, white feathered wings, a bald head and glowing eyes, in white and gold armour"),
    "plapperndes-hundertmaul": ("a gibbering mouther", "an amorphous mound of pale flesh covered with many mouths and many eyes"),
    "plesiosaurier": ("a plesiosaurus", "a marine reptile with a long neck, a small head with sharp teeth and flippers, underwater"),
    "pony": ("a pony", "a real pony with a shaggy mane"),
    "priester": ("a human priest", "a kind but determined face, a chain shirt over a white and gold tunic and a holy symbol"),
    "pseudodrache": ("a pseudodragon", "a tiny red-brown dragon the size of a cat with big golden eyes and a long tail with a barbed tip"),
    "purpurwurm": ("a purple worm", "a gigantic purple worm with a huge round mouth full of teeth bursting from the earth"),
    "quasit": ("a quasit", "a tiny green-skinned demon with small horns, a pointed tail, clawed hands and a mischievous face"),
    "quipper": ("a quipper", "a small piranha-like fish with sharp teeth, underwater"),
    "quippernschwarm": ("a swarm of quippers", "many small piranha-like fish with sharp teeth, underwater"),
    "rabe": ("a raven", "a real raven with glossy black feathers"),
    "rabenschwarm-variante-insektenschwarm": ("a swarm of ravens", "a swirling flock of many black ravens"),
    "rakshasa": ("a rakshasa", "a fiend with the head of a tiger, wearing fine silk robes and jewellery"),
    "ratte": ("a rat", "a real brown rat"),
    "rattenschwarm": ("a swarm of rats", "a teeming mass of many brown rats"),
    "reh": ("a deer", "a real deer with brown fur and antlers"),
    "reitpferd": ("a riding horse", "a real brown horse with a dark mane"),
    "remorhaz": ("a remorhaz", "a huge centipede-like monster with an icy blue-white shell, a red-hot glowing back and large mandibles"),
    "riesenadler": ("a giant eagle", "a huge eagle with brown-golden feathers and a fierce noble face"),
    "riesenaffe": ("a giant ape", "an enormous powerful ape with dark fur"),
    "riesendachs": ("a giant badger", "a huge badger with grey fur and a black and white striped face"),
    "rieseneber": ("a giant boar", "a huge boar with bristly dark fur and huge tusks"),
    "rieseneidechse": ("a giant lizard", "a huge lizard with green scales"),
    "riesenelch": ("a giant elk", "a huge elk with enormous antlers"),
    "rieseneule": ("a giant owl", "a huge owl with brown and white feathers and large wise eyes"),
    "riesenfeuerkaefer": ("a giant fire beetle", "a large black beetle with two glowing orange glands above its eyes"),
    "riesenfledermaus": ("a giant bat", "a huge bat with leathery wings and a fanged snarling face"),
    "riesenfrosch": ("a giant frog", "a huge frog with green slimy skin and golden eyes"),
    "riesengeier": ("a giant vulture", "a huge vulture with a bald head and dark feathers"),
    "riesengiftschlange": ("a giant venomous snake", "a huge venomous snake with patterned scales and bared fangs"),
    "riesenhai": ("a giant shark", "a huge shark with a gaping jaw and rows of teeth, underwater"),
    "riesenhyaene": ("a giant hyena", "a huge hyena with spotted fur and a powerful jaw"),
    "riesenkrabbe": ("a giant crab", "a huge crab with a hard red shell and big pincers"),
    "riesenkrokodil": ("a giant crocodile", "a huge crocodile with rough scales and a huge open jaw"),
    "riesenkroete": ("a giant toad", "a huge toad with warty brown skin and golden eyes"),
    "riesenoktopus": ("a giant octopus", "a huge octopus with red skin and huge tentacles, underwater"),
    "riesenratte-variante-kranke-riesenratte": ("a giant rat", "a huge rat with mangy brown fur, red eyes and long yellow teeth"),
    "riesenseepferdchen": ("a giant sea horse", "a huge sea horse with a long snout and fins, underwater"),
    "riesenskorpion": ("a giant scorpion", "a huge scorpion with a black shell, big pincers and a raised stinger"),
    "riesenspinne": ("a giant spider", "a huge spider with a hairy black body and many eyes"),
    "riesentausendfuessler": ("a giant centipede", "a huge centipede with a segmented red-brown body and many legs"),
    "riesenwespe": ("a giant wasp", "a huge wasp with yellow and black stripes and a large stinger"),
    "riesenwiesel": ("a giant weasel", "a huge weasel with brown fur"),
    "riesenwolfsspinne": ("a giant wolf spider", "a huge wolf spider with a hairy brown body and many eyes"),
    "riesenwuergeschlange": ("a giant constrictor snake", "a huge constrictor snake with patterned scales"),
    "riesenziege": ("a giant goat", "a huge goat with long curved horns and shaggy fur"),
    "riffhai": ("a reef shark", "a real reef shark, underwater"),
    "ritter": ("a human knight", "a noble determined face, full steel plate armour with a surcoat and an open helmet"),
    "roch": ("a roc", "a gigantic bird of prey with brown feathers and a huge hooked beak"),
    "rostmonster": ("a rust monster", "an insect-like creature with a rust-red armoured body, a long tail ending in a propeller-like fin and two feathery antennae"),
    "saebelzahntiger": ("a saber-toothed tiger", "a big cat with orange striped fur and long sabre teeth"),
    "sahuagin": ("a sahuagin", "a fish-like humanoid with green scales, a fanged shark-like mouth, fins on its head and dark eyes"),
    "salamander": ("a salamander", "a fiery creature with the upper body of a humanoid with red scales and a spiky crest and the lower body of a long snake, surrounded by flames"),
    "satyr": ("a satyr", "a fey with curly hair, small horns and a grin, wearing a leather vest, with the legs of a goat"),
    "schakal": ("a jackal", "a real jackal with sandy fur"),
    "schatten": ("a shadow", "a dark living shadow in the shape of a human with two faint glowing eyes"),
    "schildwaechter": ("a shield guardian", "a hulking armoured golem construct with broad metal shoulders, holding a large shield in one fist, an amulet glowing in its chest"),
    "schlaeger": ("a human thug", "a broken nose, a shaved head and a scarred face, in brown leather armour"),
    "schreckenswolf": ("a dire wolf", "a huge wolf with dark grey fur and glowing yellow eyes"),
    "schreckgespenst": ("a specter", "a translucent dark spectral figure in tattered shadows with hollow glowing eyes"),
    "schreckhahn": ("a cockatrice", "a creature with the head and body of a rooster, bat-like wings and a long lizard-like tail"),
    "schwarzbaer": ("a black bear", "a real black bear"),
    "schwarzer-blob": ("a black pudding", "a glossy black mound of thick slime slowly dripping over stone"),
    "seeoger": ("a merrow", "an aquatic ogre with green scaly skin, webbed hands and seaweed in its hair"),
    "seepferdchen": ("a sea horse", "a real sea horse, underwater"),
    "seevettel": ("a sea hag", "a hideous old woman with green scaly skin, matted seaweed hair and webbed hands, in rags"),
    "seiler": ("a roper", "a stalagmite-like creature of grey stone-coloured rubbery flesh with one large eye, a toothy mouth and long tentacles"),
    "skelett": ("a skeleton", "an undead human skeleton with glowing eye sockets, wearing scraps of rusty armour"),
    "skorpion": ("a scorpion", "a real scorpion"),
    "solar": ("a solar", "a radiant winged angel with golden skin, white feathered wings and flowing golden robes"),
    "spaeher": ("a human scout", "a hood, a sharp-eyed alert face and brown leather armour, a bow over the shoulder"),
    "spinne": ("a spider", "a real spider"),
    "spion": ("a human spy", "a sly face, a dark hood and plain travelling clothes"),
    "stammeskrieger": ("a human tribal warrior", "face paint, a feathered headdress and fur and hide armour"),
    "staub-mephit": ("a dust mephit", "a small impish creature of swirling grey dust with tiny wings"),
    "steingolem": ("a stone golem", "a huge humanoid statue carved of grey stone with a stern carved face"),
    "steinriese": ("a stone giant", "a tall lean giant with grey stone-like skin and a hairless head with a stern face"),
    "streitross": ("a warhorse", "a powerful real warhorse with a dark coat"),
    "streitross-skelett": ("a warhorse skeleton", "an undead horse skeleton with glowing eyes and scraps of rusty barding"),
    "sturmriese": ("a storm giant", "a huge regal giant with pale violet-blue skin and long silver hair and beard, in scale mail, with lightning around"),
    "sukkubus-inkubus": ("a succubus", "a fiend with a beautiful but cruel face, small horns and bat-like wings, wearing a dark elegant robe"),
    "tarraske": ("the tarrasque", "a gigantic reptilian monster with a massive armoured carapace, two long horns and a huge jaw"),
    "teppich-des-erstickens": ("a rug of smothering", "an ornate patterned carpet rising into the air like a living creature"),
    "teufelchen": ("an imp", "a tiny red devil with bat wings, small horns and a barbed tail"),
    "tiger": ("a tiger", "a real tiger with orange and black stripes"),
    "todesalb": ("a wraith", "a dark spectral figure in a tattered black cloak with a hollow face and two glowing red eyes"),
    "todeshund": ("a death dog", "a two-headed black dog with sharp teeth"),
    "triceratops": ("a triceratops", "a real triceratops dinosaur with three horns and a bony frill"),
    "troll": ("a troll", "a tall gaunt green-skinned giant with long arms, a long nose, warty skin and stringy black hair"),
    "tyrannosaurus-rex": ("a tyrannosaurus rex", "a real tyrannosaurus rex dinosaur with a huge toothy jaw"),
    "unsichtbarer-pirscher": ("an invisible stalker", "a barely visible whirl of air in vaguely humanoid shape, outlined only by swirling dust"),
    "vampir": ("a vampire", "a pale aristocratic undead with red eyes, sharp fangs and slicked-back black hair, in an elegant dark coat with a high collar"),
    "vampirbrut": ("a vampire spawn", "a pale feral undead with red eyes and fangs, in torn dirty clothes"),
    "veteran": ("a human veteran", "a scarred weathered face with grey stubble, in splint armour"),
    "violetter-pilz": ("a violet fungus", "a purple mushroom-like creature with several whip-like tendrils"),
    "vrock": ("a vrock", "a fiend with the body of a human-sized vulture, grey feathers, a long neck and clawed arms"),
    "wache": ("a human town guard", "a chain shirt over a tunic, a helmet and a spear"),
    "waechternaga": ("a guardian naga", "a huge golden-green serpent with a serene human-like face"),
    "wasserelementar": ("a water elemental", "a tall coiling pillar of clear seawater and foam with two small glowing blue lights inside"),
    "werbaer": ("a werebear", "a huge hybrid of a man and a brown bear with a bear head and shaggy fur"),
    "wereber": ("a wereboar", "a hybrid of a man and a boar with a boar head with tusks and bristly fur"),
    "werratte": ("a wererat", "a hybrid of a man and a rat with a rat head, whiskers and brown fur, in plain clothes"),
    "wertiger": ("a weretiger", "a hybrid of a man and a tiger with a tiger head and striped fur, in plain clothes"),
    "werwolf": ("a werewolf", "a hybrid of a man and a wolf with a snarling wolf head and grey fur"),
    "wiesel": ("a weasel", "a real weasel"),
    "winterwolf": ("a winter wolf", "a large wolf with snow-white fur, pale blue eyes and frosty breath"),
    "wolf": ("a wolf", "a real grey wolf with thick fur and amber eyes"),
    "wolkenriese": ("a cloud giant", "a huge regal giant with pale skin, silver-white hair, a jewelled circlet and fine clothes"),
    "worg": ("a worg", "a huge evil wolf with dark brown fur, glowing red eyes and a savage snarl"),
    "wuergeschlange": ("a constrictor snake", "a real constrictor snake with patterned scales"),
    "wyvern": ("a wyvern", "a dragon-like creature with two legs, large bat-like wings, a long neck and a tail with a venomous stinger, brown-green scales"),
    "xorn": ("a xorn", "a creature of living rock with a wide mouth on top of its head, three arms and three eyes around its body"),
    "zentaur": ("a centaur", "the upper body of a man with long hair and a leather vest and the lower body of a horse, carrying a bow"),
    "ziege": ("a goat", "a real goat"),
    "zombie": ("a zombie", "a rotting undead human with grey skin, empty eyes and torn rags"),
    "zugpferd": ("a draft horse", "a real heavy draft horse"),
}

# Probelauf 1: unbekannte Gestalten macht FLUX zu Menschen oder Köpfen → Körperbau ausdrücklich beschreiben
L.update({
    "eulenbaer": ("an owlbear", "a monstrous hybrid: the massive shaggy body, shoulders and clawed paws of a huge brown bear, topped by the feathered head of a giant owl with a hooked beak and big round eyes; feathers on the head and neck turn into thick bear fur on the shoulders"),
    "gallertwuerfel": ("a gelatinous cube", "a creature that is nothing but a huge, perfectly cube-shaped block of transparent green jelly filling a dungeon corridor, with old bones, coins and a rusty sword floating inside it; it has no face, no head and no limbs"),
    "irrlicht": ("a will-o'-wisp", "a small floating orb of pale blue-white light hovering over a dark misty swamp, glowing softly with a faint halo; it is only light, with no face, no body and no figure inside"),
    "mimik": ("a mimic", "a monster disguised as a wooden treasure chest: the chest itself is the mouth – its lid is the upper jaw lined with sharp teeth, the box is the lower jaw – and a long sticky purple tongue hangs out over the front; the wood has a few small eyes in its grain; there is no head, no face and no body besides the chest"),
    "otyugh": ("an otyugh", "a bloated round grey-brown sack of a body, as big as a cart, standing on three short thick elephant-like legs; it has no arms and no head, only two long rubbery tentacles ending in spiked leaf-shaped pads and a single eye on a long thin stalk growing from the top; a huge gaping mouth full of jagged teeth sits in the middle of its body"),
    "rostmonster": ("a rust monster", "a four-legged insect-like beast the size of a pony, walking on all fours with its belly close to the ground; a low armadillo-like body covered in rust-red and orange armour plates, a long armoured tail ending in a flat paddle-shaped fin, and on its blunt head two long feathery antennae; it is an animal, not a person"),
    "xorn": ("a xorn", "a squat barrel-shaped creature of speckled grey and brown stone with no neck and no head; three long clawed arms are spaced evenly around its body, three stone-lidded eyes sit around its upper rim, and a huge round mouth full of teeth opens on the very top of its body"),
    "seiler": ("a roper", "a creature that looks like a tall cone-shaped stalagmite of grey stone-coloured rubbery flesh, with one big yellow eye and a wide mouth full of teeth in the middle of the cone; long thin sticky tentacles reach out from its sides; it has no arms, no legs and no head"),
    "mantler": ("a cloaker", "a flat flying creature shaped like a manta ray, made of black leathery skin that looks like an old cloak, with two glowing red eyes and a row of small bone-white claws along its upper edge; no person is wearing it"),
    "belebte-ruestung": ("an animated suit of armour", "an empty suit of dented steel plate armour standing by itself; behind the open visor of the helmet there is only black darkness, no face and no person inside"),
    "grauschlick": ("a gray ooze", "a flat spreading puddle of glistening grey slime on a stone floor, like spilled wet cement, with slow ripples and a few bubbles; nothing rises out of it, it has no head, no face and no limbs"),
    "ockergallerte": ("an ochre jelly", "a low creeping blob of translucent yellow-brown slime oozing over a stone floor, with a few bubbles inside; nothing rises out of it, it has no head, no face and no limbs"),
    "schwarzer-blob": ("a black pudding", "a glossy black mound of thick tar-like slime slowly dripping over stone steps; nothing rises out of it, it has no head, no face and no limbs"),
    "landhai": ("a bulette", "a massive armoured beast walking on four short thick legs, with a huge shark-like head and a gaping mouth full of teeth, its body covered in heavy grey-blue armour plates and a tall fin on its back; it is an animal, not a person"),
    "teppich-des-erstickens": ("a rug of smothering", "a richly patterned red and gold carpet rising and rippling in the air like a living creature, its corners curling like grasping hands; no person is under or in it"),
    "fliegendes-schwert": ("a flying sword", "a magical steel longsword floating upright in the air by itself, its blade gleaming; nobody is holding it"),
    "unsichtbarer-pirscher": ("an invisible stalker", "an invisible creature revealed only by a tall whirlwind of grey dust and dry leaves swirling in a vague outline in an empty stone hall; the wall behind is clearly visible through the swirl; there is no skin, no face and no solid body"),
    "ankheg": ("an ankheg", "a giant burrowing insect with six legs and a hard brown chitinous shell, crawling out of the earth, long antennae and huge mandibles dripping with acid"),
    "grick": ("a grick", "a long ringed grey-green worm coiled on a cave floor, its head a beaked mouth surrounded by four tentacles"),
    "duestermantel": ("a darkmantle", "a small octopus-like creature with a dark cloak-like web of skin between its tentacles and a hard beak, hanging from a cave ceiling"),
    "harpyie": ("a harpy", "a wild-haired woman with a hideous face, dark feathers covering her body, large feathered wings in place of arms and taloned bird legs"),
})

# Sichtung aller 317 (2026-10-03): FLUX nimmt bekannte Begriffe zu wörtlich (Sphinx → Löwenkopf, Werwolf → Wolf,
# Seepferdchen → Pferd, Zentaur → Pferdekopf) – Mischwesen Teil für Teil beschreiben und sagen, was es NICHT ist.
# Heilssymbole neutral (Sonnenscheibe statt Kreuz), keine Federhauben realer Völker, Meervolk bekleidet.
L.update({
    "aboleth": ("an aboleth", "a huge primeval fish-like creature like a giant eel crossed with a catfish, seen from the side in dark water: a long slimy blue-green body covered in mucus, a broad flat head with three glowing red eyes stacked one above the other along its side, and four long whip-like tentacles growing from its body behind the head; it has no arms, no human face and no tentacles around its mouth"),
    "akolyth": ("a human acolyte", "a young devout face, a simple hooded grey robe and a wooden sun-disc amulet with carved rays on a cord"),
    "priester": ("a human priest", "a kind but determined face, a chain shirt over a white and gold tunic and a round golden sun-disc amulet with rays on a chain"),
    "androsphinx": ("an androsphinx", "a huge winged lion whose head is the head of a bearded human man: a human face with a nose, lips and a long braided beard, wearing a regal striped headdress; from the neck down a lion's body with tawny fur and great feathered wings; it does not have a lion's face"),
    "gynosphinx": ("a gynosphinx", "a winged lion whose head is the head of a wise human woman: a human face with dark eyes and lips framed by long hair and a golden headdress; from the neck down a lion's body with tawny fur and great feathered wings; it does not have a lion's face"),
    "mantikor": ("a manticore", "a monster with the body of a lion and the face of a bearded human man with a wild lion-like mane and a mouth full of sharp teeth, large leathery dragon wings and a long tail ending in a cluster of iron spikes; its face is human, not a lion's face"),
    "chuul": ("a chuul", "a giant armoured crustacean like an upright lobster standing on four jointed legs, with a hard greenish-brown segmented shell, two huge pincers and a cluster of small writhing tentacles around its mouth; it has no human face and no human body"),
    "dachs": ("a badger", "a real European badger: a stocky grey body with short legs and a white head with two broad black stripes running from the nose over the eyes to the ears; it is a badger, not a raccoon"),
    "riesendachs": ("a giant badger", "a huge European badger: a stocky grey body with short strong legs and big claws, a white head with two broad black stripes running from the nose over the eyes to the ears; it is a badger, not a raccoon"),
    "hyaene": ("a hyena", "a real spotted hyena: sandy fur with dark spots, a sloping back, a short bristly mane along the neck, big round ears and a short dark muzzle with a strong jaw; it is a hyena, not a dog"),
    "riesenhyaene": ("a giant hyena", "a huge spotted hyena: sandy fur with dark spots, a sloping back, a bristly mane along the neck, big round ears and a short dark muzzle with a powerful jaw; it is a hyena, not a dog"),
    "ettin": ("an ettin", "a huge brutish giant with two equally large ugly heads side by side on one pair of broad shoulders, each head with its own tangled hair and crooked teeth, wearing crude furs and leather"),
    "glabrezu": ("a glabrezu", "a large fiend with a dog-like horned head and rough red-brown skin; it has four arms: two small human-like arms with clawed hands in front of its chest and two huge arms ending in giant crab-like pincers"),
    "greif": ("a griffon", "a beast whose front half is a golden eagle – eagle head with a hooked beak, feathered neck, great wings and front talons – and whose back half is a lion with tawny fur, hind legs with paws and a long tufted tail"),
    "grimlock": ("a grimlock", "a grey-skinned humanoid with no eyes at all – smooth skin covers the places where the eyes should be – a scarred face, sharp teeth and long black hair, in simple rags"),
    "lamia": ("a lamia", "a creature whose upper body is a dark-haired woman in a silk top with golden jewellery and whose waist joins seamlessly onto the body of a lion with four lion legs and a tail; she has no human legs and there is no separate lion"),
    "lehmgolem": ("a clay golem", "a large crude humanoid figure sculpted from wet reddish-brown clay, its surface rough and unfinished with finger marks and cracks, a simple lumpy face with two hollow eye holes and runes scratched into its chest; it is a sculpture, not a person"),
    "meervolk": ("a merfolk", "a person with blue-green skin and seaweed and shells in the hair, wearing a fitted top of woven seaweed with shell plates that fully covers the chest; the lower body is a fish tail"),
    "modernder-schlurfer": ("a shambling mound", "a hulking heap of rotting vegetation – vines, moss, roots, dead leaves and mud – in a rough humanoid shape, dripping swamp water; it has no face, no eyes and no human features"),
    "pavian": ("a baboon", "a real baboon with olive-brown fur, a long dog-like muzzle, close-set eyes under a heavy brow and a thick mane on the shoulders"),
    "pseudodrache": ("a pseudodragon", "a tiny red-brown dragon the size of a cat, with a reptile snout, two small horns, leathery bat-like wings, scaly skin, four clawed legs and a long tail with a barbed tip; it is a dragon, not a cat"),
    "riesenseepferdchen": ("a giant sea horse", "a giant sea horse underwater: the fish with a long tube-shaped snout, a curled prehensile tail, bony ridged plates along its upright body and small fins; it is a fish, not a horse"),
    "seepferdchen": ("a sea horse", "a small sea horse underwater: the fish with a long tube-shaped snout, a curled tail, bony ridged plates along its upright body and small fins; it is a fish, not a horse"),
    "riesenwolfsspinne": ("a giant wolf spider", "a huge hairy brown and grey spider with eight long legs, a large abdomen, two big glossy front eyes among its eight eyes and fangs; it is only a spider, with no fur face, no snout and no mammal features"),
    "saebelzahntiger": ("a saber-toothed tiger", "a big prehistoric cat with tawny fur and faint stripes and two very long curved sabre-like upper fangs reaching far below its chin"),
    "schwarzer-blob": ("a black pudding", "a glossy black mound of thick tar-like slime spreading over a flat stone floor, with a few bubbles; nothing rises out of it, it has no head, no face and no limbs"),
    "stammeskrieger": ("a human tribal warrior", "face paint of white clay, a necklace of animal teeth and bones, braided hair and fur and hide armour"),
    "todeshund": ("a death dog", "a lean black dog with two heads side by side on one body, both heads snarling with bared sharp teeth"),
    "waechternaga": ("a guardian naga", "a huge golden-green serpent whose head is the serene face of a human woman with long dark hair; below the head there is only the long scaly snake body, no arms; its face is human, not a snake's head"),
    "werbaer": ("a werebear", "a towering hybrid of a man and a brown bear: a bear's head on a broad humanoid body with shaggy brown fur and clawed hands, wearing the torn remains of a linen shirt"),
    "wereber": ("a wereboar", "a hybrid of a man and a boar: a boar's head with tusks on a stocky humanoid body with bristly fur and clawed hands, wearing the torn remains of a leather vest"),
    "werwolf": ("a werewolf", "a hybrid of a man and a wolf: a snarling wolf's head on a lean humanoid body with grey fur and clawed hands, wearing the torn remains of a shirt"),
    "zentaur": ("a centaur", "the head and torso of a man with long hair and a leather vest rising from the front of a horse's body where a horse's neck would be, with four horse legs and a horse tail, holding a bow; his head is human"),
})

# Zweite Runde (2026-10-03): Steht der englische Name im Prompt, malt FLUX das bekannte Bild („manticore“ = Flügellöwe,
# „lamia“ = Frau neben Löwe) – auch gegen jede Beschreibung. Bei diesen Wesen deshalb ohne Namen, nur beschreibend.
L.update({
    "mantikor": ("a monster with the face of an old bearded man on the body of a winged lion", "the face is clearly the face of a bearded old human man with wrinkles, a human nose and human eyes, framed by a wild grey mane of hair, his mouth full of sharp teeth; from the neck down it has the body of a lion with tawny fur and paws, large leathery bat-like wings and a long tail ending in a cluster of iron spikes"),
    "gynosphinx": ("a winged lion with the head of a human woman", "a calm human woman's face with dark eyes, long dark hair and a golden headdress; directly below her chin begins the body of a lion: a broad jewelled golden collar covers her neck and chest, followed by thick tawny lion fur, lion forelegs with paws and great feathered wings; she rests on her belly with her front paws stretched forward"),
    "lamia": ("a creature that is half woman and half lion", "built like a centaur, but with the body of a lion instead of a horse: the upper body of a dark-haired woman in a red silk top with golden jewellery rises from the front of a lion's body exactly where the lion's neck and head would be; behind her waist the lion's body continues with four lion legs with paws and a long tail; the lion has no head of its own; she is not riding a lion and not standing next to one"),
    "glabrezu": ("a huge four-armed demon with giant crab pincers", "a towering fiend with rough red-brown skin and a dog-like horned head; it has four arms: its two upper arms are enormous and end in giant crab claws instead of hands, and below them two smaller human-like arms with clawed fingers are held in front of its belly"),
    "grimlock": ("an eyeless grey humanoid", "a blind cave-dwelling humanoid with grey stony skin; its face has no eyes and no eye sockets at all – smooth unbroken grey skin runs from the forehead straight down to the nose where the eyes should be – a wide mouth with sharp teeth and long black hair, wearing simple rags"),
    "lehmgolem": ("a crude statue of reddish-brown clay that has come to life", "a huge hulking humanoid figure roughly sculpted from wet reddish-brown clay like an unfinished potter's statue: a lumpy shapeless head with two hollow holes for eyes, no nose, no hair, no skin and no human features, its clay surface covered in finger marks, cracks and smears, runes scratched into its chest"),
    "pavian": ("a baboon", "a real olive baboon walking on all fours: olive-brown fur, a long narrow dog-like muzzle as long as the rest of its head, close-set eyes under a heavy brow, a thick mane over the shoulders and a curved tail"),
    # dritte Runde: „head and upper body“ machte aus jedem Tongolem einen glatzköpfigen Mann
    "lehmgolem": ("a giant golem built from lumps of wet red clay", "a huge lumbering figure piled together from heavy slabs and lumps of wet reddish-brown clay, with thick column-like legs and long arms ending in blunt mitten-like hands; its small round head has no face except two hollow holes and a crude slit for a mouth; the clay is cracked, smeared with finger marks and dripping; it looks like a giant unfinished pottery sculpture, not a person and not a muscular man"),
    "lamia": ("a creature that is half woman and half lion, seen from the side", "seen from the side like a centaur, but with the body of a lion instead of a horse: the long lion body with tawny fur, four lion legs with paws and a long tufted tail stretches out behind her, and the upper body of a dark-haired woman in a red silk top with golden jewellery rises straight up from the front of the lion's body, where its neck would be; the lion has no head of its own; she is not riding a lion and not standing next to one"),
})

# Rückmeldung des Nutzers zu 40 Wesen (2026-10-03): weniger menschlich, richtige Körperzahl/-teile, Vierbeiner auf
# vier Beinen von der Seite, keine Metallrüstung bei Tieren. Namen mit starkem Vorwissen (gorgon = Medusa, werewolf,
# tarrasque, succubus …) stehen nicht mehr im Motiv – nur die Beschreibung.
L.update({
    "chuul": ("a giant armoured crustacean", "a huge lobster-like creature on four jointed legs with a hard greenish-brown segmented shell; its front limbs are two enormous crab pincers – it has no hands and no human arms – and a cluster of small writhing tentacles hangs around its mouth"),
    "erdelementar": ("an earth elemental", "a hulking mass of boulders, packed earth and broken rock with roots and gravel trickling from it, only roughly shaped like a huge body with massive rock fists; its head is a craggy lump of stone with two glowing amber eyes deep in a crack; there is no human face, no nose, no mouth and no muscles"),
    "feuerelementar": ("a fire elemental", "a roaring pillar of living fire that only vaguely suggests a body, with long tongues of flame as arms; two bright white points of light burn inside the blaze where eyes would be; there is no human face, no nose, no mouth and no skin"),
    "wasserelementar": ("a water elemental", "a huge wave of seawater rising out of a pool on a stone floor and curling over like a breaking wave, full of foam and spray; two small glowing blue lights shine inside the water; there is no face, no head and no human shape"),
    "erwachter-baum": ("an old oak tree that has come to life", "a gnarled old oak walking on its roots, its branches like long arms; its face is formed only by the bark: two dark knotholes as eyes and a long crack in the bark as a mouth, framed by moss; no nose, no lips, no human skin and no human features"),
    "erwachter-busch": ("a small shrub that has come to life", "a small leafy shrub standing on little roots like feet; among its leaves two small dark hollows look like eyes; no human face, no nose and no mouth, only leaves, twigs and roots"),
    "ettin": ("a two-headed giant", "a huge brutish giant with two separate heads, each on its own thick neck, growing side by side from one pair of broad shoulders; the two heads have different faces – one bearded and scowling, one bald and snarling – both with tangled hair and crooked teeth; he wears crude furs and leather"),
    "fliegendes-schwert": ("a magic longsword flying through the air", "a steel longsword hovering high in the air in the middle of an empty stone hall, point downwards, with nobody holding it; a faint magical glow surrounds the blade and its small shadow lies on the floor far below, showing that it floats"),
    "glabrezu": ("a four-armed demon whose upper arms end in giant crab pincers", "a towering demon with rough red-brown skin and a dog-like horned head; it has four arms and all four grow from its body: from its shoulders grow two huge long arms that end in giant crab pincers instead of hands, and from its chest, just below them, grow two smaller human-like arms with clawed hands; nothing floats beside its head"),
    "gorgone": ("a huge bull made of iron", "a huge bull standing on four legs, its whole body covered in overlapping iron-grey metal plates like dragon scales, with large curved horns and green poisonous vapour curling from its nostrils; it is an animal on four legs, not standing upright"),
    "grick": ("a giant eyeless worm with tentacles", "a long ringed grey-green worm coiled on a cave floor; its head has no eyes at all, only a hard beaked mouth surrounded by four tentacles"),
    "gynosphinx": ("a winged lion with the head of a human woman", "her face is calm and beautiful with dark eyes; her long dark hair becomes a thick lion's mane that flows down over her neck and shoulders into the tawny fur of the lion's body, so that face and body join naturally; a golden headdress, great feathered wings and lion's paws stretched forward"),
    "lamia": ("a creature that is half woman and half lioness", "built like a centaur: from the hips down she is a lioness with four lion legs, tawny fur and a long tufted tail; at her hips the fur gives way smoothly to the skin of her human upper body, so that both parts join naturally; long dark hair, a red silk top and golden jewellery; the lioness has no head of its own; she is not riding a lion"),
    "mantikor": ("a winged lion with the face of an old bearded man", "the weathered human face with a grey beard and fierce eyes is framed by a wild lion's mane that flows down into the tawny fur of the body, so that face and body join naturally; leathery bat-like wings and a long tail ending in a cluster of iron spikes"),
    "hydra": ("a hydra", "a huge reptilian monster with a heavy crocodile-like body on four short legs and a long tail; from its shoulders grow five long snake-like necks of the same length, each ending in an identical snarling reptile head of the same size; green scales; the whole creature is shown from a little distance"),
    "kobold": ("a small dragon-like humanoid", "a small reptilian humanoid the size of a child, with a dragon-like snout, two small curved horns, rust-red scales, bright yellow eyes and a long tail, wearing a simple leather tunic and holding a small spear; a lively, slightly cheeky expression"),
    "kreischer": ("a cluster of giant shrieking mushrooms", "a cluster of giant pale violet mushrooms growing from a dark cave floor, the largest as tall as a man; its broad cap is split by a gaping slit like a wide-open mouth, as if it were shrieking; it has no eyes, no legs and no animal body"),
    "landhai": ("a huge shark-headed burrowing beast", "a massive beast bursting out of the earth on four short thick legs, with a huge shark-like head and a gaping mouth full of teeth; its back is covered in thick natural grey-blue plates of bone and horn like an armadillo shell, with a tall dorsal fin; it wears no metal and no armour – the plates are part of its body"),
    "lemure": ("a melting blob of flesh-coloured slime", "a melting, oozing mound of pinkish-grey slime dragging itself over a stone floor, its surface bubbling and dripping; only a vague hint of a sad face is sunk into the slime; it has no human body, no arms and no shoulders"),
    "mimik": ("a mimic", "a monster disguised as a wooden treasure chest: its lid is the upper jaw lined with sharp teeth and a long sticky purple tongue hangs out over the front; two large yellow eyes with slit pupils have opened on the front of the lid and a few smaller eyes peer from the grain of the wood; no head and no body besides the chest"),
    "modernder-schlurfer": ("a hulking heap of rotting plants", "a heap of rotting vegetation – vines, moss, roots, dead leaves and mud – shaped like a huge hunched body with long trailing arms; its head is just a mound of leaves and roots with no face at all: no eyes, no nose and no mouth"),
    "nalfeshnee": ("a huge obese demon with an ape's body and a boar's head", "the obese, hunched body of a giant ape with long powerful arms, a sagging pot belly and coarse brown fur, and the head of a wild boar with tusks and a snout; on its back sit two ridiculously small feathered wings, far too small to carry it"),
    "otyugh": ("an otyugh", "a bloated round grey-brown body as big as a cart on three short thick legs; two long thick tentacles like elephant trunks reach out from its body like arms, each ending in a spiked leaf-shaped pad; a single eye on a long thin stalk grows from the top and a huge gaping mouth full of jagged teeth sits in the middle of its body; it has no head and no human arms"),
    "planetar": ("a large angel", "emerald-green skin, white feathered wings, a bald head and glowing eyes, wearing a smooth flowing white robe and a plain golden breastplate without any anatomical details"),
    "riesengiftschlange": ("a giant venomous snake", "a huge slender venomous snake coiled on a stone floor, with a narrow head without any hood, patterned scales and bared fangs; its long body is thin like a thick rope"),
    "wuergeschlange": ("a constrictor snake", "a long slender constrictor snake coiled in loops on a stone floor, with a narrow head without any hood and patterned brown and olive scales; its body is thin like a thick rope"),
    "rieseneidechse": ("a giant lizard", "a giant monitor lizard walking low to the ground on all four legs, with a long tail and a forked tongue; it is an animal on four legs, not standing upright"),
    "riesenkrokodil": ("a giant crocodile", "a huge crocodile lying low on all four short legs on a muddy riverbank, its long tail stretched out behind and its jaws slightly open; it is an animal on four legs, not standing upright"),
    "schatten": ("a living shadow", "a dark smoky silhouette only vaguely shaped like a person, its edges dissolving into drifting black smoke; it has no face except two faint pale glowing eyes, and the wall behind shows faintly through it"),
    "steingolem": ("a giant animated statue of carved stone blocks", "a huge statue built of massive carved grey stone blocks with visible joints and chisel marks, a square block-like head carved into a stylised mask-like face like an ancient temple guardian and glowing runes on its chest; no skin and no human features"),
    "steinriese": ("a towering giant of living stone", "his skin looks like weathered grey granite with cracks, mineral veins and patches of lichen; a long angular face like a carved cliff, deep-set dark eyes and no hair; a simple hide garment; he is clearly a creature of stone and mountains, not an ordinary man"),
    "sukkubus-inkubus": ("a beautiful winged fiend", "a stunningly beautiful young woman with flawless pale skin, large dark eyes, dark red lips and long glossy black hair, small elegant curved horns and folded bat-like wings, wearing an elegant high-necked dark gown; a confident, alluring smile"),
    "tarraske": ("a colossal dinosaur-like monster", "a gigantic reptile standing on two massive hind legs like a huge dinosaur, its back covered by a thick natural bony shell, two long horns pointing forward from its head, rows of spikes, a huge jaw full of teeth and a long spiked tail; it towers over ruined buildings far smaller than it; it wears no metal and no armour"),
    "todesalb": ("a ghostly wraith", "a dark translucent spirit in a tattered hooded shroud that fades into drifting mist at the edges, through which the wall behind is faintly visible; inside the hood only darkness and two glowing red eyes; no skull, no face and no solid body"),
    "triceratops": ("a triceratops", "a real triceratops dinosaur standing on four legs, with a large bony frill, two long horns above the eyes, a short nose horn and a beak, rough brown-green skin; a prehistoric animal"),
    "waechternaga": ("a giant serpent with a wise serpentine face", "a huge golden-green serpent whose head has only a hint of human wisdom: smooth scaled skin, large golden eyes with slit pupils, a flat snake-like nose, no hair but a fan of scaled golden frills around the head; below the head only the long scaly snake body"),
    "werwolf": ("a huge wolf-like monster standing upright", "a full wolf's head with a long snout and fangs, its whole body covered in thick grey fur, long arms with clawed paws, bent wolf legs and a tail; only a few rags of a torn shirt hang from it; it looks far more like a wolf than like a man"),
    "wolkenriese": ("a towering cloud giant", "a giant many times taller than a man standing among the clouds of a mountain peak, with pale skin with a faint blue tint, long silver hair and beard braided with silver rings, a jewelled circlet and flowing robes in white and sky blue; clouds swirl around his legs and a tiny castle far below shows his enormous size"),
    "xorn": ("a xorn", "a squat barrel-shaped creature of speckled grey and brown stone with no head and no neck; on the very top of its body a huge round mouth full of teeth opens upwards; three stone-lidded eyes are spaced evenly around the sides of its body; three long arms, each ending in three clawed fingers, are spaced evenly around its upper body, and it stands on three short thick legs, each with three stubby toes"),
    "zentaur": ("a centaur", "the head and torso of a man with long hair and a leather vest rising from the front of a horse's body where a horse's neck would be, with four horse legs and a horse tail; a longbow and a quiver of arrows are slung across his back and his hands are empty"),
})
# Zweiter Anlauf für 11 Wesen: „mane“ zog Gesichter zum Löwen (Gynosphinx, Mantikor), Seitenansicht machte aus dem
# Zentaur einen Reiter, „eyes“+„head“ gab dem Erdelementar wieder ein Gesicht, „runes“ wurden zu Schriftzeichen.
L.update({
    "gynosphinx": ("a sphinx with the head of a human woman", "a lying lion with great feathered wings whose head is the head of a calm, beautiful human woman with dark eyes; she wears a striped royal headcloth of gold and blue that falls in two broad bands over her shoulders onto the lion's chest and hides where her neck joins the lion's body; tawny lion fur and lion paws stretched forward; her face is completely human, with human ears and no fur"),
    "mantikor": ("a winged lion with the face of an old bearded man", "its head is the weathered face of a fierce old man with deep wrinkles, a broad nose, human ears and a mouth full of sharp teeth; his long wild grey hair and long beard grow down into the thick tawny fur of the lion's chest and shoulders, so the face sits naturally on the lion's body; no lion snout and no lion ears; large leathery bat-like wings and a long tail ending in a cluster of iron spikes"),
    "lamia": ("a creature that is half woman and half lioness", "built like a centaur: from the hips down she is a lioness with four lion legs, tawny fur and a long tufted tail; above her hips rises the upper body of a woman with a calm, completely human face, human ears and long dark hair, wearing a high-necked red silk blouse and golden jewellery; the lioness has no head of its own"),
    "ettin": ("a two-headed giant", "a huge brutish giant with very broad shoulders from which two separate thick necks grow, one on the left and one on the right, with a clear gap of air between the two heads; one head is bearded and scowling, the other bald and snarling, both with crooked teeth; he wears crude furs and leather"),
    "xorn": ("a xorn", "a squat barrel-shaped creature of speckled grey and brown stone with no head and no neck; a huge round mouth full of teeth opens upwards on the very top of its body; three stone-lidded eyes are spaced evenly around its sides; three long arms grow from its upper body – one to the left, one to the right and one to the back – each ending in three clawed fingers; it stands on three short thick legs, each with three stubby toes"),
    "zentaur": ("a centaur", "a single creature whose body is a brown horse with four legs and a tail, but where the horse's neck and head would be, the torso of a man rises instead; the creature has only one head, the human head with long hair; there is no horse head and no horse neck; he wears a leather vest, a longbow and a quiver are slung across his back and his hands are empty"),
    "lemure": ("a melting blob of flesh-coloured slime", "a melting, oozing mound of pinkish-grey slime dragging itself over a stone floor, bubbling and dripping; it has no human head and no face – only two small dark hollow pits near its top; no hair, no nose, no mouth, no body and no arms"),
    "triceratops": ("a triceratops", "a real triceratops dinosaur, huge and heavy like a rhinoceros, with a massive barrel-shaped body, four short thick legs like an elephant's, a large bony neck frill, two long horns above the eyes, a short nose horn, a parrot-like beak and a thick tail; rough grey-brown skin; a prehistoric animal as in a natural history painting"),
    "erdelementar": ("an earth elemental", "a towering mound of boulders, packed earth, broken rock and roots, roughly shaped like a hunched giant with massive rock fists; on top sits a single jagged boulder in which two amber lights glow deep in a crack; there is no face, no brow, no nose, no mouth and no muscles, only rough stone and earth"),
    "landhai": ("a huge shark-headed burrowing beast", "a massive beast bursting out of the earth on four short thick legs, with a huge shark-like head and a gaping mouth full of teeth; its back is covered by a rough natural shell of bone-coloured horn plates like a tortoise shell, with no rivets, no bands and no spikes, and a tall dorsal fin; its skin is grey-blue and leathery; it wears no metal and no armour"),
    "steingolem": ("a giant animated statue of carved stone blocks", "a huge statue built of massive carved grey stone blocks with visible joints and chisel marks, a square block-like head carved into a stylised mask-like face like an ancient temple guardian, and a single round glowing gem set in the middle of its chest; there are no runes, no letters and no writing anywhere; no skin and no human features"),
})

# Dritter Anlauf: Xorn zeigte 4 statt 3 Arme (ein Arm muss zum Betrachter zeigen, sonst ist er verdeckt), Zentaur
# wurde von vorn zum Mann mit Pferdebeinen und von der Seite zum Reiter – Fassung aus Runde 1 (die einen echten Zentaur
# ergab) mit locker gehaltenem Bogen; Gynosphinx mit „sphinx“ im Motiv bekam Löwenzüge.
L.update({
    "xorn": ("a xorn, a three-legged stone creature", "a squat barrel-shaped creature of speckled grey and brown stone with no head and no neck; a huge round mouth full of teeth opens upwards on the very top of its body; it has exactly three arms, spaced around its body like the spokes of a wheel: one reaching out to the left, one reaching out to the right and one reaching straight forward towards the viewer; each arm ends in a hand with exactly three long clawed fingers; it stands on exactly three short thick legs – one at the left, one at the right and one in the middle at the front – each foot with three stubby toes; three stone-lidded eyes sit around its sides, one between each pair of arms"),
    "zentaur": ("a centaur", "the head and torso of a man with long hair and a leather vest rising from the front of a horse's body where a horse's neck would be, with four horse legs and a horse tail; there is no horse head; in his left hand he holds a longbow upright by the grip in the middle of the bow, its lower tip resting near the ground like a staff; his right hand rests on his hip; a quiver of arrows on his back"),
    "gynosphinx": ("a winged lion with the head of a human woman", "her face is completely human – a calm, beautiful woman's face with dark eyes, a straight human nose, human lips and human ears, without any fur or whiskers; she wears a striped royal headcloth of gold and blue that falls in two broad bands over her shoulders onto the lion's chest and covers where her neck joins the lion's body; below it the body of a lion with tawny fur, great feathered wings and paws stretched forward"),
})
# Zweite Rückmeldung des Nutzers (9 Wesen): Körperbau aus Beschreibungen und gemeinfreien Darstellungen abgeleitet,
# nicht aus fremden Bildern übernommen (Lizenz) – Hydra nach griechischer Sage (Schlangenleib im Sumpf, keine Beine),
# Xorn: Maul oben, drei Arme und drei Augen im Kreis um das Maul, drei Stummelbeine; Landhai: geschossförmig, gepanzert,
# Rückenkamm, vier Grabbeine – ohne das Wort „shark“.
L.update({
    "glabrezu": ("a four-armed demon with gigantic crab pincers", "a towering demon with rough red-brown skin and a dog-like horned head; its two upper arms are enormous – twice as long as its other arms and as thick as its legs – and end in gigantic crab pincers, each pincer as big as its own torso, raised high on both sides of its head; below them, two smaller human-like arms with clawed hands are held in front of its belly; all four arms grow from its body"),
    "lamia": ("a creature that is half woman and half lioness", "built like a centaur: from the hips down she is a lioness with four lion legs, tawny fur and a long tufted tail; above her hips rises the upper body of a woman with long dark hair, a completely human face and human ears; she has two human arms with human hands – one hand rests on her hip, the other hangs at her side; she wears a red silk blouse with long sleeves and golden jewellery; the lioness has no head of its own"),
    "hydra": ("a many-headed serpent monster of the swamp", "a gigantic serpent whose thick scaly body lies coiled in the dark water of a misty swamp; from its body rise seven long sinuous serpent necks, all of the same length and thickness, each ending in an identical snake head with fangs, a forked tongue and a small crest of spines; the heads rear up and twist in different directions; dark green and bronze scales; it has no legs; its heads are snake heads with short snouts, not crocodile heads"),
    "landhai": ("a huge armoured burrowing beast", "a massive bullet-shaped predator bursting up through rocky ground in a spray of dirt and stones; its heavy pointed head is covered by a helmet of armour plates and has a huge mouth with several rows of dull ivory teeth and small yellow eyes set in dark skin; its whole back and its thick muscular tail are covered in overlapping armour plates of grey-blue and blue-green, which rise along the spine into a tall fin-like crest; four thick legs with large sharp digging claws; it lives in the earth, not in water"),
    "mimik": ("a mimic disguised as a treasure chest", "a wooden treasure chest that is itself a living monster: the half-open lid is its upper jaw and the box is its lower jaw, and both edges are lined with rows of large sharp teeth; a long sticky purple tongue lolls out over the front; the wood looks slightly alive, with a few round yellowish eye-spots in its grain; sticky grey tentacle-like pseudopods reach out from both sides and grip the floor; there is no separate creature or face inside the chest"),
    "steingolem": ("a towering stone guardian statue come to life", "a huge humanoid statue carved from a single block of weathered grey granite, shaped like an armoured knight: carved stone plates on its shoulders and chest, huge carved fists, and a smooth helmet-like head without a face, showing only a narrow eye slit with a faint blue glow; the stone is old, cracked and patched with moss, heavy and monumental like an ancient temple guardian; it is clearly stone, not flesh"),
    "sukkubus-inkubus": ("a beautiful seductive winged fiend", "a stunningly beautiful young woman with flawless pale skin, large dark eyes, dark red lips and long glossy black hair, small elegant curved horns and large bat-like wings; she wears an elegant, revealing gown of dark red silk with a low neckline, bare shoulders and a high slit; a confident, alluring, seductive smile"),
    "xorn": ("a xorn", "a squat, wide, barrel-shaped creature whose pebbly body looks like rough brown and grey stone; on the very top of its body is a huge round mouth ringed with sharp teeth; three long arms grow from the top of its body around this mouth, evenly spaced, reaching up and outwards, each ending in sharp talons; between the arms, also around the mouth, sit its three large eyes; its wide body rests on three short stumpy legs; it has no head and no face"),
    "zentaur": ("a centaur", "the head and torso of a man with long hair and a leather vest rising from the front of a horse's body where a horse's neck would be, with four horse legs and a horse tail; there is no horse head; he carries no weapons – no bow, no arrows and no quiver; his bare arms are folded across his chest"),
})
# Vierter Anlauf (Lamia, Xorn, Landhai): Lamia von vorn = Frau auf zwei Löwenbeinen → von der Seite mit Löwinnenleib;
# Xorn ohne Augen → Augen als große leuchtende Kugeln am Maulrand; Landhai: „armour plates“ = Metall → Knochenschuppen.
L.update({
    "lamia": ("a creature that is half woman and half lioness, seen from the side", "seen from the side like a centaur: the long body of a lioness with tawny fur stretches horizontally across the picture, standing on four lion legs with paws, a long tufted tail behind; where the lioness's neck would be, the upper body of a woman rises straight up from its front; she has a human face with long dark hair that covers her ears, two human arms with human hands – one hand holds a golden goblet, the other rests on the lioness's flank – and wears a red silk blouse and golden jewellery; the lioness has no head of its own and no animal ears"),
    "xorn": ("a xorn", "a squat, wide, barrel-shaped creature whose pebbly body looks like rough brown and grey stone; on the very top of its body is a huge round mouth ringed with sharp teeth; around the rim of this mouth sit three large round glowing amber eyes, evenly spaced; between the eyes, three long arms grow from the top of its body, reaching up and outwards, each ending in three sharp talons; its wide body rests on three short stumpy legs; it has no head and no face"),
    "landhai": ("a huge burrowing beast", "a massive bullet-shaped predator bursting up through rocky ground in a spray of dirt and stones; its heavy wedge-shaped head has a huge mouth with several rows of dull ivory teeth and small yellow eyes set in dark skin; its back and thick tail are covered in rough, natural bony scutes like a crocodile's or an armadillo's – matte, organic, earth-coloured grey-blue and blue-green, scratched and caked with dirt, part of its living skin – rising along the spine into a tall jagged fin-like crest of bone; four thick legs with huge digging claws; no metal, no rivets, no straps"),
})
# Fünfter Anlauf Lamia: wörtlich wie der Zentaur, der damit gelang (Oberkörper „where a horse's neck would be“)
L["lamia"] = ("a centaur-like creature with the lower body of a lioness", "the head and torso of a woman with long dark hair rising from the front of a lioness's body where a lioness's neck would be, with four lion legs with paws and a long tufted tail; there is no lion head; she has a completely human face and her ears are hidden under her long hair; she wears a red silk blouse and golden jewellery; her bare human arms are folded across her chest")
# Dritte Rückmeldung (2026-10-03): Der Nutzer zeigte Bilder als Orientierung. Diese sind urheberrechtlich geschützt –
# übernommen ist nur der allgemeine Körperbau in eigenen Worten (der auch aus den SRD-Beschreibungen folgt);
# Farben, Pose, Ausrüstung (Sattel) und Malstil sind eigene. Die Bilder selbst gehen nie ins Modell.
L.update({
    "hydra": ("a five-headed hydra", "a huge wingless dragon-like reptile standing on four short, powerful legs with large claws; from its broad shoulders rise five long, sinuous serpentine necks of the same length, each ending in a fierce dragon-like head with an open mouth full of sharp teeth, a red forked tongue and a frill of spines along the back of the head and neck; the necks curl and twist in different directions; rough scales of deep moss green and dark bronze; a long tapering tail; it is a many-headed dragon, not a crocodile and not a snake coil"),
    "landhai": ("a huge armoured burrowing beast", "a massive, heavy-bodied predator built like a living battering ram: its pointed, bullet-shaped head is covered by one enormous smooth bony plate that sweeps back from the tip of its snout over its head like a huge beak or helmet, with small eyes peering from beneath the rear edge of this plate and a wide mouth of jagged teeth underneath its front; its back and sides are covered by large, overlapping bony plates with sharp, flaring edges that rise along the spine like a ridge of shields; the plates are slate-grey with a faint blue-green sheen, the skin between them is leathery, wrinkled and earth-brown; four short, thick, powerful legs, the front feet ending in huge curved digging claws; a short, thick, plated tail; no fin, no metal, no saddle and no straps"),
    "mimik": ("a mimic disguised as a treasure chest", "a wooden treasure chest with grey iron bands, iron corners and a keyhole on the front that has come alive: its lid has opened into a huge grinning mouth – the edge of the lid and the edge of the box are lined all the way round with rows of large, thick, blunt ivory teeth of uneven size set in dark purple gums; a long, thick purple tongue lolls out of the mouth; along the top edge of the lid sits a row of four small glowing amber eyes set in warty, bumpy brown skin that bulges out between the planks; no tentacles, no legs and no other creature inside"),
    "xorn": ("a xorn", "a hulking, squat creature as wide as it is tall, with no head and no neck; its whole body is covered in pebbly, rounded, stone-like scales of reddish brown, like a mass of river pebbles; a huge wide mouth gapes open across the very top of its body, lined with jagged white teeth; three thick, muscular arms grow from its upper body, spaced evenly around the mouth, each ending in a hand with three long curved talons, reaching up and out; one large round amber eye sits in the middle of its front, just below the mouth and between two of the arms, while its other eyes face away to the sides and back; it stands on three short, thick, pillar-like legs with clawed toes"),
})
# Zweiter Versuch nach Referenz: „dragon-like“ brachte Flügel und aufrechten Stand, „slate-grey with a sheen“ wieder Metall
L.update({
    "hydra": ("a five-headed hydra", "a huge reptile with a heavy, low, horizontal body like a gigantic monitor lizard, standing on all four bent, clawed legs with its belly close to the ground; it has no wings at all; from its broad shoulders rise five long, sinuous serpentine necks of the same length, each ending in a fierce dragon-like head with an open mouth full of sharp teeth, a red forked tongue and a frill of spines along the back of the head and neck; the necks curl and twist in different directions; rough scales of deep moss green and dark bronze; a long tapering tail lies on the ground behind it"),
    "landhai": ("a huge armoured burrowing beast", "a massive, heavy, low-slung predator built like a living battering ram: its pointed, bullet-shaped head is covered by one enormous bony plate that sweeps back from the tip of its snout over its head like a huge beak, with small eyes peering from beneath its rear edge and a wide mouth of jagged teeth underneath its front; its back and sides are covered by large, overlapping plates of rough natural horn and bone like a tortoise's shell or a pangolin's scales – matte, chipped, scratched, with growth rings, coloured dusty ochre, beige and dull grey-green, caked with dirt – their edges flaring up along the spine like a ridge of shields; the skin between the plates is leathery, wrinkled and earth-brown; four short, thick, powerful legs, the front feet ending in huge curved digging claws; a short, thick tail; nothing is made of metal; no fin, no saddle and no straps"),
})
# Dritter Versuch nach Referenz: Xorn zeigte nur zwei Arme → Arme asymmetrisch einzeln verorten; Landhai-Platten wirkten
# glatt/gebuckelt → scharfkantige, splitternde Ränder wie Schieferscherben, ohne Löcher und Punkte
L.update({
    "xorn": ("a xorn with three arms", "a hulking, squat creature as wide as it is tall, with no head and no neck; its whole body is covered in pebbly, rounded, stone-like scales of reddish brown, like a mass of river pebbles; a huge wide mouth gapes open across the very top of its body, lined with jagged white teeth; it has exactly three thick, muscular arms with long curved talons: the first arm is raised high on its left side, the second arm is raised high on its right side, and the third arm grows from its lower right side and hangs down beside its body; one large round amber eye sits in the middle of its front just below the mouth; it stands on three short, thick, pillar-like legs with clawed toes"),
    "landhai": ("a huge armoured burrowing beast", "a massive, heavy, low-slung predator built like a living battering ram: its pointed, bullet-shaped head is covered by one enormous bony plate that sweeps back from the tip of its snout over its head like a huge beak, with small eyes beneath its rear edge and a wide mouth of jagged teeth underneath; its back and sides are covered by large, overlapping plates of natural shell whose edges are sharp, jagged and splintered like broken slate, flaring up along the spine into a ridge of sharp shard-like points; the plates are smooth, without holes, dots or spots, coloured in dark grey-green with streaks of dusty ochre; the skin between the plates is leathery, wrinkled and earth-brown; four short, thick, powerful legs with huge curved digging claws; a short, thick, tapering tail; nothing is made of metal; no fin, no saddle and no straps"),
})
ANSICHTEN_EXTRA = {
    "zentaur": ["in three-quarter view, turned towards the right side of the picture, so that his human upper body and the whole horse body with all four legs are visible",
                "seen from the side, facing right, with his human head turned towards the viewer",
                "in three-quarter view, turned towards the right side of the picture, looking at the viewer"],
    "xorn": ["seen from the front, its arms raised", "in three-quarter view, turned slightly towards the right side of the picture, its arms reaching out",
             "seen from the front and slightly from below, towering, its arms raised"],
    "hydra": ["seen from the side, facing right, walking on all four legs, its five heads rearing up in different directions",
              "in three-quarter view, turned towards the right side of the picture, crouching low on all four legs",
              "seen from the side, facing right, crouching low on all four legs, its five heads snapping in different directions"],
    "landhai": ["bursting up out of rocky ground at a steep angle, its plated head pointing upwards, in a cloud of dust and flying stones",
                "seen from the side, facing right, charging low across dusty ground",
                "in three-quarter view, turned towards the right side of the picture, half emerged from the earth"],
    "mimik": ["in three-quarter view, its open mouth facing the viewer", "seen from the front", "in three-quarter view, turned towards the right side of the picture"],
    "lamia": ["in three-quarter view, turned towards the right side of the picture, so that her human upper body and the whole lioness body with all four legs are visible",
              "seen from the side, facing right, with her human head turned towards the viewer",
              "in three-quarter view, turned towards the right side of the picture, looking at the viewer"],
}

# Blickrichtung je Wesen: Vierbeiner und Schlangen von der Seite, damit Beine und Körper stimmen
SEITLICH = ["seen from the side, facing right", "in three-quarter view, turned towards the right side of the picture",
            "seen from the side, facing right, its head turned towards the viewer"]
ANSICHTEN = {k: SEITLICH for k in ("gorgone", "rieseneidechse", "riesenkrokodil", "triceratops", "riesengiftschlange",
                                   "wuergeschlange", "landhai", "chuul", "hydra", "tarraske")}
# Xorn und Zentaur: eigene Blickrichtungen (siehe ANSICHTEN_EXTRA oben)
ANSICHTEN.update(ANSICHTEN_EXTRA)

# mehr vom Körper zeigen, wenn Kopf und Schultern die Gestalt nicht erklären
RAHMEN = {
    "eulenbaer": "head, shoulders and upper body", "otyugh": GANZ, "rostmonster": GANZ, "mimik": GANZ, "xorn": GANZ,
    "seiler": GANZ, "mantler": GANZ, "belebte-ruestung": "head and upper body", "landhai": GANZ, "unsichtbarer-pirscher": GANZ,
    "ankheg": GANZ, "grick": GANZ, "duestermantel": GANZ, "drinne": "head and upper body", "zentaur": "head and upper body",
    "harpyie": "head and upper body", "lamia": "head and upper body", "marilith": "head and upper body",
    "meervolk": "head and upper body", "chimaere": "the three heads and front body",
    # Sichtung 2026-10-03
    "aboleth": GANZ, "chuul": GANZ, "greif": GANZ, "lamia": GANZ, "zentaur": GANZ, "pseudodrache": GANZ,
    "riesenseepferdchen": GANZ, "seepferdchen": GANZ, "riesenwolfsspinne": GANZ, "modernder-schlurfer": GANZ,
    "androsphinx": "head and upper body", "gynosphinx": "head and upper body", "mantikor": "head and upper body",
    "glabrezu": "head and upper body", "waechternaga": "head and upper body", "werbaer": "head and upper body",
    "wereber": "head and upper body", "werwolf": "head and upper body",
    "gynosphinx": GANZ, "pavian": GANZ, "lehmgolem": GANZ, "grimlock": "head and shoulders",
    # Rückmeldung des Nutzers 2026-10-03
    "erdelementar": GANZ, "feuerelementar": GANZ, "erwachter-baum": GANZ, "erwachter-busch": GANZ,
    "ettin": "both heads and the upper body", "glabrezu": "head, chest and all four arms", "gorgone": GANZ,
    "mantikor": GANZ, "hydra": GANZ, "kobold": GANZ, "nalfeshnee": GANZ, "planetar": "head and upper body",
    "riesengiftschlange": GANZ, "wuergeschlange": GANZ, "rieseneidechse": GANZ, "riesenkrokodil": GANZ,
    "schatten": GANZ, "steingolem": GANZ, "steinriese": "head and upper body", "sukkubus-inkubus": "head and upper body",
    "tarraske": GANZ, "todesalb": "head and upper body", "triceratops": GANZ, "waechternaga": "head and upper body",
    "werwolf": GANZ, "wolkenriese": GANZ,
}

# ganze Gestalt statt Kopf und Schultern
GANZE_GESTALT = {"fledermausschwarm", "insektenschwarm", "rattenschwarm", "giftschlangenschwarm", "quippernschwarm",
                 "rabenschwarm-variante-insektenschwarm", "gallertwuerfel", "grauschlick", "ockergallerte", "schwarzer-blob",
                 "irrlicht", "luftelementar", "wasserelementar", "plapperndes-hundertmaul", "mimik", "fliegendes-schwert",
                 "teppich-des-erstickens", "kreischer", "violetter-pilz", "lemure"}
VARIANTEN = ["seen from the front, looking straight at the viewer",
             "in three-quarter view turned towards the right side of the picture, looking at the viewer",
             "in three-quarter view turned towards the right side of the picture, gazing to the right"]

jobs, fehlt = [], []
for jid, j in alt.items():
    if "drache" in jid and jid not in ("drachenschildkroete", "pseudodrache", "halbroter-drachenveteran"):
        alter = next(a for a in ALTER if jid.startswith(a) or jid.endswith(a))
        farbe = next(f for f in FARBEN if f in jid.replace("ae", "").replace("drachennestling", ""))
        en_f, f_text = FARBEN[farbe]
        en_a, a_text = ALTER[alter]
        if alter == "nestling":
            motiv = f"a {en_f} dragon wyrmling"
        else:
            motiv = f"an {en_a} {en_f} dragon" if en_a[0] in "aeiou" else f"a {en_a} {en_f} dragon"
        look, rahmen = a_text.format(f=f_text), "head and long neck"
    elif jid in L:
        motiv, look = L[jid]
        rahmen = RAHMEN.get(jid) or (GANZ if jid in GANZE_GESTALT else "head and shoulders")
    else:
        fehlt.append(jid)
        continue
    jobs.append({"id": jid, "name": j["name"], "art": "portraet", "stil": "fantasy-dunkel", "motiv": motiv,
                 "rahmen": rahmen, "looks": [f"{look}, {v}" for v in ANSICHTEN.get(jid, VARIANTEN)],
                 "typ": j.get("type"), "groesse": j.get("size"), "neg": j.get("neg", "")})
if fehlt:
    raise SystemExit(f"Ohne Beschreibung: {fehlt}")
(SDXL / "jobs-flux-portraets.json").write_text(json.dumps(jobs, ensure_ascii=False, indent=1), encoding="utf-8")
print(len(jobs), "Porträt-Aufträge geschrieben")
for d in ("junger-roter-drache", "kupferdrachennestling", "uralter-messingdrache", "ausgewachsener-weisser-drache"):
    x = next(y for y in jobs if y["id"] == d)
    print(" ", d, "→", x["motiv"], "|", x["looks"][0][:90])
